[supervisord]
nodaemon=true

[program:streamer]
command=/usr/local/bin/streamer.sh
autostart=true
autorestart=true
stderr_logfile=/var/log/streamer.err.log
stdout_logfile=/var/log/streamer.out.log


[program:socat0]
command=socat -d -d TCP4-LISTEN:54321,reuseaddr OPEN:/dev/serial0,raw,echo=0,clocal #Changed FORK to OPEN because the container suddenly can't change the baudrate on the serial port, can't seem to find the issue, possibly a software update(?)
autostart=true
autorestart=true
stderr_logfile=/var/log/socat0.err.log
stdout_logfile=/var/log/socat0.out.log
